
import type { Course } from './types';

// This file contains placeholder data for courses until a full
// content management system for instructors is implemented.

export const placeholderCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Advanced React & TypeScript for SaaS',
    description: 'Deep dive into building scalable and maintainable SaaS applications using advanced React patterns and TypeScript.',
    thumbnail_url: 'https://picsum.photos/seed/course1/600/400',
    instructor_id: 'user-123',
    instructor_name: 'Chris P. Bacon',
    instructor_avatar: 'https://i.pravatar.cc/150?u=chrisp',
    price: 199.99,
    tags: ['React', 'TypeScript', 'SaaS'],
    level: 'advanced',
    rating: 4.9,
    student_count: 1250,
    created_at: new Date().toISOString(),
  },
  {
    id: 'course-2',
    title: 'UI/UX Design Fundamentals for Developers',
    description: 'Learn the core principles of UI/UX design to build more intuitive and user-friendly applications. No design background required.',
    thumbnail_url: 'https://picsum.photos/seed/course2/600/400',
    instructor_id: 'user-456',
    instructor_name: 'Jane Dough',
    instructor_avatar: 'https://i.pravatar.cc/150?u=janedough',
    price: 99.99,
    tags: ['UI/UX', 'Figma', 'Design Systems'],
    level: 'beginner',
    rating: 4.8,
    student_count: 8430,
    created_at: new Date().toISOString(),
  },
  {
    id: 'course-3',
    title: 'The Art of SEO Copywriting',
    description: 'Master the skill of writing compelling copy that ranks on search engines and converts readers into customers.',
    thumbnail_url: 'https://picsum.photos/seed/course3/600/400',
    instructor_id: 'user-789',
    instructor_name: 'Mark Etting',
    instructor_avatar: 'https://i.pravatar.cc/150?u=marketting',
    price: 149.99,
    tags: ['Copywriting', 'SEO', 'Content Marketing'],
    level: 'intermediate',
    rating: 4.9,
    student_count: 5621,
    created_at: new Date().toISOString(),
  },
  {
    id: 'course-4',
    title: 'Firebase for Modern Web Applications',
    description: 'A comprehensive guide to leveraging the full power of Firebase, including Firestore, Auth, and Cloud Functions.',
    thumbnail_url: 'https://picsum.photos/seed/course4/600/400',
    instructor_id: 'user-101',
    instructor_name: 'Dev Eloper',
    instructor_avatar: 'https://i.pravatar.cc/150?u=developer',
    price: 249.99,
    tags: ['Firebase', 'Next.js', 'Serverless'],
    level: 'intermediate',
    rating: 4.7,
    student_count: 3102,
    created_at: new Date().toISOString(),
  },
   {
    id: 'course-5',
    title: 'Freelance Business Masterclass',
    description: 'Learn how to find high-value clients, price your services, and build a sustainable freelance business.',
    thumbnail_url: 'https://picsum.photos/seed/course5/600/400',
    instructor_id: 'user-202',
    instructor_name: 'Anita Business',
    instructor_avatar: 'https://i.pravatar.cc/150?u=anitabusiness',
    price: 299.99,
    tags: ['Business', 'Freelancing', 'Client Management'],
    level: 'beginner',
    rating: 4.9,
    student_count: 11054,
    created_at: new Date().toISOString(),
  },
  {
    id: 'course-6',
    title: 'Motion Design with After Effects',
    description: 'Bring your designs to life with stunning animations and motion graphics using Adobe After Effects.',
    thumbnail_url: 'https://picsum.photos/seed/course6/600/400',
    instructor_id: 'user-303',
    instructor_name: 'Moe Shen',
    instructor_avatar: 'https://i.pravatar.cc/150?u=moeshen',
    price: 179.99,
    tags: ['Animation', 'After Effects', 'Motion Graphics'],
    level: 'intermediate',
    rating: 4.8,
    student_count: 4200,
    created_at: new Date().toISOString(),
  },
  {
    id: 'course-7',
    title: 'Python for Data Science & ML',
    description: 'From NumPy to TensorFlow, this course is your complete guide to becoming a data scientist with Python.',
    thumbnail_url: 'https://picsum.photos/seed/course7/600/400',
    instructor_id: 'user-404',
    instructor_name: 'Al Gorithm',
    instructor_avatar: 'https://i.pravatar.cc/150?u=algorithm',
    price: 219.99,
    tags: ['Python', 'Data Science', 'Machine Learning'],
    level: 'advanced',
    rating: 4.9,
    student_count: 9876,
    created_at: new Date().toISOString(),
  },
  {
    id: 'course-8',
    title: 'Building a Brand on Social Media',
    description: 'A step-by-step guide to creating a powerful brand presence and engaging community on social media platforms.',
    thumbnail_url: 'https://picsum.photos/seed/course8/600/400',
    instructor_id: 'user-505',
    instructor_name: 'Brenda Image',
    instructor_avatar: 'https://i.pravatar.cc/150?u=brendaimage',
    price: 129.99,
    tags: ['Social Media', 'Branding', 'Marketing'],
    level: 'beginner',
    rating: 4.7,
    student_count: 15320,
    created_at: new Date().toISOString(),
  },
];
