// This file can be used for shared TypeScript types across your app.
// The 'FieldValue' import from Firebase is no longer needed as Supabase
// handles timestamps automatically at the database level.

// Example of a type for your 'users' table, generated by Supabase
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          username: string | null;
          display_name: string | null;
          photo_url: string | null;
          bio: string | null;
          created_at: string; // Supabase stores this as an ISO string
          updated_at: string;
        }
      }
      // ... add other table types here
    }
  }
}
